### ISSUE TITLE
Use strict breaks import order

### ISSUE THREAD

**Issue by pegak** [trivago/prettier-plugin-sort-imports#148] opened 2022-04-11 16:58 UTC
**Your Environment**
 * **Prettier version**: 2.6.2
 * **node version**: 16.14.0
 * **package manager**: 8.3.1
 * **IDE**: CLI

**Describe the bug**

`'use strict'` is pushed below imports.

**To Reproduce**

1. Try to format this code:
```typescript
'use strict'

import type { Period } from './Period'
```
2. Bug appears.
```typescript
import type { Period } from './Period'

;('use strict')
```

**Expected behavior**

Keep `'use strict'` above.

**Screenshots, code sample, etc**

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**
```json
{
  "semi": false,
  "trailingComma": "none",
  "singleQuote": true,
  "printWidth": 640,
  "importOrder": ["@riot/metaplayer", "^[./]"],
  "importOrderSeparation": true
}
```

**Error log**

**Contribute to @trivago/prettier-plugin-sort-imports**

- [ ] I'm willing to fix this bug 🥇

**Comment by IanVS** [comment] 2022-04-27 14:02
FIWI, this is fixed in a fork: https://github.com/IanVS/prettier-plugin-sort-imports/releases/tag/v3.3.1.

**Comment by ayusharma** [comment] 2023-02-24 20:48
Can you give a try to v4.1.1 ? 

Please feel free to reopen if the issue is still valid.

**Closed by ayusharma** 2023-02-24 20:48 UTC
Labels: investigation
